### ISSUE TITLE
Panel example gives me very high flashing window

### ISSUE THREAD

**Issue by bleuge** [tinyBigGAMES/raylib#2]
I can see content draw ok, but the window is flashing white very fast until I hit esc.
Maybe my graphics card? 
If i click the window title bar, the flashing is paused, so I can see the big black background alternating the real content.

My PC: Lenovo Thinkpad x220, W10 LTSC x64, GPU Intel Graphics HD 4000, if fully supports a lot of standards, so maybe it's not the gpu? 

Very interesting project by the way, wish I can test it against other options.

**Comment by jarroddavis68** [comment]
Hi, thanks for checking it out and sorry to hear you are having some issues. Let's see if we can get them resolved. First, maybe comment out this line:
```Pascal
SetConfigFlags(FLAG_WINDOW_HIGHDPI or FLAG_MSAA_4X_HINT);
```
And see if this makes any difference. If it does, add each flag back until the issue shows up again.

I will be adding more examples also.

**Comment by jarroddavis68** [comment]
I see. Since then, I've added a few more examples. Can you tell me if there are any issues with them? The panel example is direct from raygui example, only converted to pascal and it actually calls the underlying C code from raygui/raylib. It may be something related to raygui itself. The only difference being pascal generated code is calling C routines. I had to make a few adjustments to accommodate the differences in the languages in a few places.

**Comment by jarroddavis68** [comment]
Oh, I think I forgot to add SetTargetFPS(60) in the panel demo. If so, can you please add it and let me know.

**Comment by jarroddavis68** [comment]
[scroll_panel.zip](https://github.com/tinyBigGAMES/raylib/files/11005942/scroll_panel.zip)
Hi, try this. It is built directly from the raylib/raygui vs2022 project.

**Comment by bleuge** [comment]
Hi, new examples worked perfectly, so, without knowing what I was doing, I compared code between examples and found the bug.

There is a double  EndDrawing call in example_render procedure.

>  EndDrawing;
>  EndDrawing;
>end;

Thanks!

**Comment by jarroddavis68** [comment]
Ahh, crap. Ok. Sorry about that. I think that was left over from when I grabbed the C code example and pasted it into the template and started to convert it in place. I never any those effects on my devbox. But good looking out for catching this. Thanks again. The copy/paste demon strikes again. LOL!

**Comment by bleuge** [comment]
Hehe, I smiled when I found it, as you said it's the typical copy+paste error I myself done thousands times . 
I am not a pro developer, just amateur loving Pascal for many years.
I am sure a good static analyzer for FPC/Delphi would catch errors like this.

**Comment by jarroddavis68** [comment]
What is also good to know is that the technique I'm using to manage the DLL behind the scenes is working properly in your dev environment. 👍🏿

**Comment by bleuge** [comment]
When I saw the big res file, I thought maybe this is the DLL and is loading it from inside exe file without droping the dll to disk? (which I think maybe could cause problems). 
I read time ago about this technique but never tried it. It works perfectly without any extra files or whatever.
